import { hash } from "bcryptjs";
import { and, eq } from "drizzle-orm";
import { db } from "../index";
import {
  collaboratorRates,
  projectMembers,
  projects,
  tasks,
  userRoles,
  users,
} from "../schema";

type SeedUserInput = {
  email: string;
  name: string;
  role: "OWNER" | "COLLABORATOR";
};

export type CoreSeedResult = {
  collaborator: typeof users.$inferSelect;
  owner: typeof users.$inferSelect;
  password: string;
  project: typeof projects.$inferSelect;
};

const seedUsers: SeedUserInput[] = [
  {
    email: process.env.SEED_OWNER_EMAIL ?? "owner@collabill.local",
    name: "Seed Owner",
    role: "OWNER",
  },
  {
    email: process.env.SEED_COLLABORATOR_EMAIL ?? "collab@collabill.local",
    name: "Seed Collaborator",
    role: "COLLABORATOR",
  },
];

const seedPassword = process.env.SEED_PASSWORD ?? "password123";

async function getOrCreateUser(input: SeedUserInput, passwordHash: string) {
  const existing = await db.query.users.findFirst({
    where: eq(users.email, input.email),
  });

  if (existing) {
    return existing;
  }

  const [created] = await db
    .insert(users)
    .values({
      email: input.email,
      name: input.name,
      passwordHash,
    })
    .returning();

  if (!created) {
    throw new Error(`Failed to create user ${input.email}`);
  }

  return created;
}

async function seedRolesAndRates(core: {
  collaborator: typeof users.$inferSelect;
  collaboratorRole: SeedUserInput["role"];
  owner: typeof users.$inferSelect;
  ownerRole: SeedUserInput["role"];
}) {
  await db
    .insert(userRoles)
    .values([
      { userId: core.owner.id, role: core.ownerRole },
      { userId: core.collaborator.id, role: core.collaboratorRole },
    ])
    .onConflictDoNothing();

  await db
    .insert(collaboratorRates)
    .values({
      userId: core.collaborator.id,
      dailyRate: "400",
      rateXs: "100",
      rateS: "200",
      rateM: "400",
      rateL: "800",
    })
    .onConflictDoUpdate({
      target: collaboratorRates.userId,
      set: {
        dailyRate: "400",
        rateXs: "100",
        rateS: "200",
        rateM: "400",
        rateL: "800",
      },
    });
}

async function getOrCreateSeedProject(ownerId: string) {
  const existing = await db.query.projects.findFirst({
    where: and(
      eq(projects.name, "Seed Project"),
      eq(projects.createdBy, ownerId),
    ),
  });

  if (existing) {
    return existing;
  }

  const [created] = await db
    .insert(projects)
    .values({
      name: "Seed Project",
      description: "Demo workspace generated by db/seeds/core.seed.ts",
      gitRepo: "https://github.com/example/collabill-seed",
      createdBy: ownerId,
    })
    .returning();

  if (!created) {
    throw new Error("Failed to create seed project.");
  }

  return created;
}

async function seedProjectMembershipAndTasks(input: {
  collaboratorId: string;
  ownerId: string;
  projectId: string;
}) {
  await db
    .insert(projectMembers)
    .values([
      { projectId: input.projectId, userId: input.ownerId },
      { projectId: input.projectId, userId: input.collaboratorId },
    ])
    .onConflictDoNothing();

  const existingTasksCount = await db.$count(
    tasks,
    eq(tasks.projectId, input.projectId),
  );

  if (existingTasksCount > 0) {
    return;
  }

  await db.insert(tasks).values([
    {
      projectId: input.projectId,
      title: "Set up project backlog",
      description: "Create initial backlog and milestones.",
      size: "S",
      priority: 1,
      status: "TODO",
      assignedTo: input.ownerId,
    },
    {
      projectId: input.projectId,
      title: "Implement first feature",
      description: "Build and validate the first seed feature.",
      size: "M",
      priority: 2,
      status: "IN_PROGRESS",
      assignedTo: input.collaboratorId,
    },
  ]);
}

export async function seedCore(): Promise<CoreSeedResult> {
  const [ownerInput, collaboratorInput] = seedUsers;

  if (!ownerInput || !collaboratorInput) {
    throw new Error("Seed users are not configured correctly.");
  }

  const passwordHash = await hash(seedPassword, 10);
  const owner = await getOrCreateUser(ownerInput, passwordHash);
  const collaborator = await getOrCreateUser(collaboratorInput, passwordHash);

  await seedRolesAndRates({
    collaborator,
    collaboratorRole: collaboratorInput.role,
    owner,
    ownerRole: ownerInput.role,
  });

  const project = await getOrCreateSeedProject(owner.id);

  await seedProjectMembershipAndTasks({
    collaboratorId: collaborator.id,
    ownerId: owner.id,
    projectId: project.id,
  });

  return { collaborator, owner, password: seedPassword, project };
}
