import { readFileSync } from "node:fs";
import { hash } from "bcryptjs";
import { and, eq } from "drizzle-orm";
import { serverEnv } from "../../packages/env/server";
import { uploadFile } from "../../packages/minio";
import { db } from "../index";
import {
  collaboratorRates,
  organizationMembers,
  organizations,
  projectMembers,
  projects,
  tasks,
  userRoles,
  users,
} from "../schema";

type SeedUserInput = {
  email: string;
  name: string;
  role: "OWNER" | "COLLABORATOR" | "ADMIN";
};

export type CoreSeedResult = {
  collaborator: typeof users.$inferSelect;
  owner: typeof users.$inferSelect;
  admin: typeof users.$inferSelect;
  password: string;
  project: typeof projects.$inferSelect;
  organization: typeof organizations.$inferSelect;
};

const seedUsers: SeedUserInput[] = [
  {
    email: serverEnv.SEED_OWNER_EMAIL,
    name: "Seed Owner",
    role: "OWNER",
  },
  {
    email: serverEnv.SEED_ADMIN_EMAIL,
    name: "Seed Admin",
    role: "ADMIN",
  },
  {
    email: serverEnv.SEED_COLLABORATOR_EMAIL,
    name: "Seed Collaborator",
    role: "COLLABORATOR",
  },
];

const seedPassword = serverEnv.SEED_PASSWORD;

async function getOrCreateUser(input: SeedUserInput, passwordHash: string) {
  const existing = await db.query.users.findFirst({
    where: eq(users.email, input.email),
  });

  if (existing) {
    return existing;
  }

  const [created] = await db
    .insert(users)
    .values({
      email: input.email,
      name: input.name,
      passwordHash,
    })
    .returning();

  if (!created) {
    throw new Error(`Failed to create user ${input.email}`);
  }

  return created;
}

async function getOrCreateOrganization(
  ownerId: string,
  adminId: string,
  collaboratorId: string,
) {
  const slug = "seed-organization";
  const existing = await db.query.organizations.findFirst({
    where: eq(organizations.slug, slug),
  });

  if (existing) {
    return existing;
  }

  const [created] = await db
    .insert(organizations)
    .values({
      name: "Seed Organization",
      slug,
    })
    .returning();

  if (!created) {
    throw new Error("Failed to create seed organization.");
  }

  await db.insert(organizationMembers).values([
    {
      organizationId: created.id,
      userId: ownerId,
      role: "OWNER",
    },
    {
      organizationId: created.id,
      userId: collaboratorId,
      role: "COLLABORATOR",
    },
    {
      organizationId: created.id,
      userId: adminId,
      role: "ADMIN",
    },
  ]);

  return created;
}

async function seedRolesAndRates(core: {
  admin: typeof users.$inferSelect;
  adminRole: SeedUserInput["role"];
  collaborator: typeof users.$inferSelect;
  collaboratorRole: SeedUserInput["role"];
  owner: typeof users.$inferSelect;
  ownerRole: SeedUserInput["role"];
  organizationId: string;
}) {
  await db
    .insert(userRoles)
    .values([
      {
        userId: core.owner.id,
        role: core.ownerRole,
        organizationId: core.organizationId,
      },
      {
        userId: core.collaborator.id,
        role: core.collaboratorRole,
        organizationId: core.organizationId,
      },
    ])
    .onConflictDoNothing();

  await db
    .insert(collaboratorRates)
    .values({
      userId: core.collaborator.id,
      organizationId: core.organizationId,
      dailyRate: "400",
      rateXs: "100",
      rateS: "200",
      rateM: "400",
      rateL: "800",
      rateXl: "1600",
    })
    .onConflictDoUpdate({
      target: [collaboratorRates.userId, collaboratorRates.organizationId],
      set: {
        dailyRate: "400",
        rateXs: "100",
        rateS: "200",
        rateM: "400",
        rateL: "800",
        rateXl: "1600",
      },
    });
}

async function getOrCreateSeedProject(ownerId: string, organizationId: string) {
  const existing = await db.query.projects.findFirst({
    where: and(
      eq(projects.name, "Seed Project"),
      eq(projects.createdBy, ownerId),
    ),
  });

  if (existing) {
    return existing;
  }

  const [created] = await db
    .insert(projects)
    .values({
      name: "Seed Project",
      description: "Demo workspace generated by db/seeds/core.seed.ts",
      gitRepo: "https://github.com/example/collabill-seed",
      baseRate: "400",
      createdAt: new Date(),
      createdBy: ownerId,
      organizationId,
    })
    .returning();

  if (!created) {
    throw new Error("Failed to create seed project.");
  }

  return created;
}

async function seedProjectMembershipAndTasks(input: {
  collaboratorId: string;
  ownerId: string;
  adminId: string;
  projectId: string;
}) {
  await db
    .insert(projectMembers)
    .values([
      { projectId: input.projectId, userId: input.ownerId },
      { projectId: input.projectId, userId: input.collaboratorId },
      { projectId: input.projectId, userId: input.adminId },
    ])
    .onConflictDoNothing();

  const existingTasksCount = await db.$count(
    tasks,
    eq(tasks.projectId, input.projectId),
  );

  if (existingTasksCount > 0) {
    return;
  }

  await db.insert(tasks).values([
    {
      projectId: input.projectId,
      title: "Set up project backlog",
      description: "Create initial backlog and milestones.",
      size: "S",
      priority: 1,
      status: "TODO",
      assignedTo: input.ownerId,
      gitRepo: "https://github.com/example/collabill-seed",
      createdAt: new Date(),
      gitBranch: "main",
    },
    {
      projectId: input.projectId,
      title: "Implement first feature",
      description: "Build and validate the first seed feature.",
      size: "M",
      priority: 2,
      status: "IN_PROGRESS",
      assignedTo: input.collaboratorId,
      gitRepo: "https://github.com/example/collabill-seed",
      createdAt: new Date(),
      gitBranch: "main",
    },
    {
      projectId: input.projectId,
      title: "Validate completed feature",
      description: "Review and validate the completed feature work.",
      size: "M",
      priority: 3,
      status: "IN_REVIEW",
      assignedTo: input.adminId,
      gitRepo: "https://github.com/example/collabill-seed",
      createdAt: new Date(),
      gitBranch: "main",
    },
  ]);
}

async function uploadSeedAvatar(userId: string) {
  try {
    const avatarPath = "/home/tophy/Documents/collabill/public/fake-avatar.png";
    const buffer = readFileSync(avatarPath);
    const fileName = "seed-avatar.png";
    const key = `avatars/${userId}/${Date.now()}-${fileName}`;
    const url = await uploadFile(buffer, key, "image/png");

    await db.update(users).set({ avatar: url }).where(eq(users.id, userId));
    return url;
  } catch (error) {
    console.error(`Failed to upload seed avatar for user ${userId}:`, error);
    return null;
  }
}

export const seedCore = async (): Promise<CoreSeedResult> => {
  const [ownerInput, adminInput, collaboratorInput] = seedUsers;

  if (!ownerInput || !collaboratorInput || !adminInput) {
    throw new Error("Seed users are not configured correctly.");
  }

  const passwordHash = await hash(seedPassword, 10);

  const owner = await getOrCreateUser(ownerInput, passwordHash);
  const collaborator = await getOrCreateUser(collaboratorInput, passwordHash);
  const admin = await getOrCreateUser(adminInput, passwordHash);

  await uploadSeedAvatar(owner.id);
  await uploadSeedAvatar(collaborator.id);
  await uploadSeedAvatar(admin.id);
  const organization = await getOrCreateOrganization(
    owner.id,
    admin.id,
    collaborator.id,
  );

  await seedRolesAndRates({
    admin,
    adminRole: adminInput.role,
    collaborator,
    collaboratorRole: collaboratorInput.role,
    owner,
    ownerRole: ownerInput.role,
    organizationId: organization.id,
  });

  const project = await getOrCreateSeedProject(owner.id, organization.id);

  await seedProjectMembershipAndTasks({
    collaboratorId: collaborator.id,
    ownerId: owner.id,
    adminId: admin.id,
    projectId: project.id,
  });

  return {
    collaborator,
    owner,
    admin,
    password: seedPassword,
    project,
    organization,
  };
};
