name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: collabill_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      minio:
        image: minio/minio
        ports:
          - "9000:9000"
          - "9001:9001"

    env:
      DATABASE_URL: postgresql://user:password@localhost:5432/collabill_db
      BREVO_API_KEY: CI_DUMMY_KEY
      MAIL_FROM: CI <ci@collabill.local>
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      S3_ENDPOINT: http://localhost:9000
      ENCRYPTION_KEY: CI_ENCRYPTION_KEY_12345678901234567890123456789012
      S3_ACCESS_KEY: admin
      S3_SECRET_KEY: password
      S3_BUCKET: my-buckets
      S3_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Biome Lint
        run: pnpm lint

      - name: Run TypeScript typecheck
        run: pnpm typecheck

      - name: Build project
        run: pnpm build
