name: Validation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql://user:password@localhost:5432/collabill_db
      NEXT_PUBLIC_S3_ENDPOINT: http://localhost:9000
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
      S3_ENDPOINT: http://localhost:9000
      ENCRYPTION_KEY: CI_ENCRYPTION_KEY_12345678901234567890123456789012
      S3_ACCESS_KEY: user
      S3_SECRET_KEY: password
      S3_BUCKET: my-buckets
      S3_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Biome Lint
        run: pnpm lint

      - name: Run TypeScript typecheck
        run: pnpm typecheck

      - name: Run unit tests
        run: pnpm test:unit

      - name: Build project
        run: pnpm build
